backend:
  name: github
  repo: OurPromises/ourpromises-web # Path to your Github repository
  branch: master # Branch to update
  site_domain: ourpromises-web.netlify.com # Your Netlify site address if different from host
media_folder: "static/images/uploads"
public_folder: "/images/uploads"